.editorconfig, README.md
=> Editorconfig

src/SistemaTCC/Controller/SemestreController.php
=> validação semestre

src/SistemaTCC/Controller/SemestreController.php
validação semestre com restrição de tipo
=> validação semestre com restrição de tipo

config/orm/SistemaTCC.Model.Aluno.dcm.yml, config/orm/SistemaTCC.Model.Professor.dcm.yml
Issue #24: corrigida a exclusão da Pessoa ao excluir um Professor ou Aluno
=> Issue #24: exclusão da Pessoa

src/SistemaTCC/Controller/AlunoController.php
aluno 
criando, editando e excluindo pronto
=> aluno finalizado

config/issue31.sql, config/orm/SistemaTCC.Model.Etapa.dcm.yml, config/orm/SistemaTCC.Model.Semestre.dcm.yml, src/SistemaTCC/Model/Etapa.php, src/SistemaTCC/Model/Semestre.php
Será necessário atualizar o banco de dados com o arquivo `config/issue31.sql` e modificar a API REST para a manutenção do semestre.
=> Modificações na modelagem de Semestre e Etapa

src/SistemaTCC/View/aluno/formulario.twig
Correção do caminho do script formulario.js
=> Correções no formulário aluno

public/app/professor/listar.css, src/SistemaTCC/View/professor/listar.twig
=> padronizando formulario

config/issue70.sql, src/SistemaTCC/Application/SistemaTCC.php, src/SistemaTCC/Controller/EtapaStatusController.php, src/SistemaTCC/Model/EtapaStatus.php, src/SistemaTCC/Model/Serializer/ObjectToJson.php, src/SistemaTCC/Provider/DoctrineOrmServiceProvider.php
Desenvolvida API Rest para o gerenciamento e uma carga inicial com alguns dados.
Deve ser validado com o pessoal de análise os possíveis valores.
#70
=> API Rest e carga inicial para status da etapa

public/app/aluno/formulario.js, public/app/professor/formulario.js
Ao incluir e editar um Aluno exibia a mesma mensagem 'Alterado', agora exibe "Incluído" ao incluir.
Ao incluir e editar um Professor exibia a mesma mensagem 'Alterado', agora exibe  "Incluído" ao incluir.
=> Ericquadros

config/insertTipoEtapa.sql, src/SistemaTCC/View/semestre/listar.twig
Semestre - correcao da issue #135.
=> Evertonnunes

src/SistemaTCC/View/semestre/formulario.twig
=> botão de cancelar no semestre 

src/SistemaTCC/Controller/TccController.php
=> Corrigido problema de abertura da listagem de TCC

public/app/index/main.css, public/app/professor/formulario.js, src/SistemaTCC/Controller/AlunoController.php, src/SistemaTCC/Controller/ProfessorController.php, src/SistemaTCC/View/aluno/formulario.twig, src/SistemaTCC/View/professor/formulario.twig
=> Correção da Issue  #151

src/SistemaTCC/View/layout.twig
=> correção de digitação TTC para TCC.

src/SistemaTCC/View/tcc/listar.twig
=> Correção na listagem do tcc cadastrados.

src/SistemaTCC/View/tcc/listar.twig
=> Correção do pull request #198.

src/SistemaTCC/Controller/AlunoController.php
=> Validação de CGU e Matrícula repetidos no cadastro de alunos

src/SistemaTCC/Controller/TccController.php
=> Rodriguesthiago

public/app/semestre/index.js, src/SistemaTCC/View/semestre/formulario.twig
=> permitir digitar livremente o nome do semestre

src/SistemaTCC/Application/SistemaTCC.php, src/SistemaTCC/Controller/IndexController.php, src/SistemaTCC/View/index/index.twig, src/SistemaTCC/View/layout.twig
=> Correção para Issue #131

flyway/sql/V013__Role_Admin.sql
=> Adição de ponto e virgula no final do comando;
